# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13b500c8597a93916982d07819a4eec7"
application_url = "https://competition-fold-holiday-mt.trycloudflare.com"
embedded = true
name = "fucking-discount"
handle = "shipping-discount-82"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://competition-fold-holiday-mt.trycloudflare.com/auth/callback",
  "https://competition-fold-holiday-mt.trycloudflare.com/auth/shopify/callback",
  "https://competition-fold-holiday-mt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
