api_version = "2025-01"

[[extensions]]
name = "t:name"
handle = "order-discount"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "purchase.order-discount.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/volume-discount/:functionId/:id"
  details = "/app/volume-discount/:functionId/:id"
